#pragma once

#define DROP_SHADOW_INACTIVATE_COLOR QColor(0,0,0,75)
#define DROP_SHADOW_INACTIVATE_BLUR_RADIUS 30

#define DROP_SHADOW_ACTIVATED_COLOR QColor(0,0,0,150)
#define DROP_SHADOW_ACTIVATED_BLUR_RADIUS 50
