variables:
  EXTRA_DNF_REPOS: |
                   [KylinSec_3.5.2_Customize_Kiran2.7]
                   name=Kiran2.7(standard_x86_64)
                   type=rpm-md
                   baseurl=http://build.kylinsec.com.cn:82/KylinSec:/3.5.2:/Customize:/Kiran2.7/standard_x86_64/
                   gpgcheck=1
                   gpgkey=http://build.kylinsec.com.cn:82/KylinSec:/3.5.2:/Customize:/Kiran2.7/standard_x86_64/repodata/repomd.xml.key
                   enabled=1
  DEFAULT_IMAGE: kylinsec-3.5.2
  RPM_BUILD_REQUIRES: 'cmake libX11-devel libxcb-devel xcb-util-devel qt5-qtbase-devel qt5-qtbase-private-devel qt5-qtx11extras-devel qt5-qtsvg-devel qt5-linguist gsettings-qt-devel kiran-qt5-integration-devel kiran-qt5-integration'

include:
  - project: 'os/ks-devops'
    ref: main
    file: '/entrypoint/develop/cmake.yml'
