//
// Created by lxh on 2021/1/22.
//

#ifndef KIRANIMAGESELECTOR_KIRAN_IMAGE_SELECTOR_GLOBAL_H
#define KIRANIMAGESELECTOR_KIRAN_IMAGE_SELECTOR_GLOBAL_H

#define IMAGE_ITEM_DEFAULT_WIDTH 212.0
#define IMAGE_ITEM_DEFAULT_HEIGHT 120.0

#define IMAGE_ITEM_ASPECT_RATIO (IMAGE_ITEM_DEFAULT_WIDTH/IMAGE_ITEM_DEFAULT_HEIGHT)

#endif //KIRANIMAGESELECTOR_KIRAN_IMAGE_SELECTOR_GLOBAL_H
